### PR TITLE
add Bein sports  channel

### PR DESCRIPTION
**Pull request by mohammedsobhi**

### CODE REVIEW

**Comment by emad-elsaid** [comment]
I don't see any live videos on this channel, was there a live video and it ended at some point?

**Comment by mohammedsobhi** [comment]
the channel has two live streams .. one of them live since (3 jan 2021)  => https://www.youtube.com/watch?v=cH1aRyPNqzA
and the other since (7 dec 2020) => https://www.youtube.com/watch?v=0Y-IRcUJi6o

https://www.youtube.com/c/beINSPORTS

**Comment by emad-elsaid** [comment]
I see why these don't appear on the page, both streams are not available for my country (Germany) this means it won't appear too on the server as the server is in germany  and the API assumes I'm asking for live videos that are available in germany. 
do you know how we can change that to return all live? because otherwise this channel won't appear at all

**Comment by mohammedsobhi** [comment]
honestly, I have no idea how to solve it.

**Pull request closed without merging**
